OLED_ENABLE = yes
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
# VIAL_INSECURE = yes
ENCODER_MAP_ENABLE = yes
RGBLIGHT_ENABLE = no
QMK_SETTINGS = yes
MOUSEKEY_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
DEBOUNCE_TYPE = sym_defer_pk
LTO_ENABLE = yes
CONVERT_TO = rp2040_ce
EXTRAFLAGS += -flto=auto -fuse-linker-plugin -ffat-lto-objects
